import type { Workbook } from "exceljs";
import { createExcelJsWorkbook } from "@/lib/exceljs";
import {
  masterDataObjectTypes,
  masterDataSheetNames,
  type MasterDataObjectType,
  type MasterDataSheetTemplate,
  type MasterDataTemplateDefinition,
} from "./types";

const MASTER_DATA_TEMPLATE_WORKBOOK_FILE_NAME = "master-data-sample.xlsx";

const masterDataSheetHeaders: Record<MasterDataObjectType, string[]> = {
  enterprise: ["Name", "Description"],
  site: [
    "Name",
    "Description",
    "RemoteExportAddress",
    "RemoteExportPlugin",
    "Enterprise",
    "IsRemote",
  ],
  facility: [
    "Name",
    "Description",
    "Type",
    "DisplayOrder",
    "DefaultCalendar",
    "TerminateOnShip",
    "Site",
    "Shipping Facilities",
  ],
  area: [
    "Name",
    "Description",
    "Type",
    "DisplayOrder",
    "Facility",
    "AreaType",
    "ParentArea",
    "Calendar",
    "Schedule",
    "IsExternal",
    "FlowPath",
    "SetFlowPath",
    "IncomingPickingPlace",
    "OutgoingPickingPlace",
    "PickingStrategy",
    "PickingSequence",
  ],
  resource: [
    "Name",
    "Description",
    "Type",
    "IsTemplate",
    "MainStateModel",
    "Vendor",
    "Model",
    "ResourceType",
    "SerialNumber",
    "Priority",
    "SortRuleSet",
    "Area",
    "DisplayOrder",
    "IsSubMaterialTrackingEnabled",
    "ProcessingType",
    "SubResources",
    "Services",
    "MaxConcurrentMaterialsInProcess",
    "AutomationAddress",
    "AutomationMode",
    "DisplayPath",
    "IsAutoGeneratePositionEnabled",
    "IsDownloadRecipeCapable",
    "IsJobManagementCapable",
    "IsNotifyRecipeSelectionChangeCapable",
    "IsProductMixAllowed",
    "IsRecipeManagementEnabled",
    "IsUploadRecipeCapable",
    "LoadPortType",
    "PositionUnitType",
    "RestrictedToMaterialForm",
    "RunningMode",
    "FixedCost",
    "CostPerHour",
    "CostPerUnit",
    "AllowTrackInScheduleOverride",
    "CanProcessInNonWorkingTime",
    "DefaultScheduleView",
    "DefaultSetupTime",
    "DefaultSetupTimeTimeScale",
    "DispatchScheduleType",
    "Efficiency",
    "MinimumBatchCapacityUsage",
    "Saturation",
    "SchedulingType",
    "Location",
    "RequireCheckInForResourceOperations",
    "HasStorageBins",
    "IsPickingPlace",
    "IsFloorLifeSafe",
    "StartFloorLifeCounterOnRetrieve",
    "EnableAutomaticReplenishment",
    "AutomaticReplenishmentTransferRequirementType",
    "TransportService",
    "ConsumableFeedType",
    "InstrumentType",
    "CalibrationStatus",
    "LastCalibrationDate",
    "InstrumentExclusiveUsage",
    "HasResourceLocations",
    "LocationType",
    "DimensionXSize",
    "DimensionYSize",
  ],
  product: [
    "Name",
    "Description",
    "Type",
    "ProductType",
    "DefaultUnits",
    "IsEnabled",
    "FlowPath",
    "Unit Conversion Factors",
    "Sub Products",
    "Binning Tree",
    "InitialUnitCost",
    "FinishedUnitCost",
    "Yield",
    "CycleTime",
    "IncludeInSchedule",
    "CapacityClass",
    "MaterialTransferMode",
    "MaterialTransferApprovalMode",
    "MaterialTransferAllowedPickup",
    "ProductGroup",
    "IsEnableForMaintenanceManagement",
    "MaintenanceManagementConsumeQuantity",
    "IsDiscrete",
    "MoistureSensitivityLevel",
    "FloorLife",
    "FloorLifeUnitOfTime",
    "RequiresApproval",
    "ApprovalRole",
    "CanSplitForPicking",
    "MaterialLogisticsDefaultRequestQuantity",
    "ConsumptionScrap",
    "AdditionalConsumptionQuantity",
    "BinCodeRequired",
    "IsEnabledForMaterialLogistics",
    "DefaultBOM",
  ],
  material: [
    "Name",
    "Description",
    "IsTemplate",
    "Type",
    "Form",
    "Facility",
    "Product",
    "FlowPath",
    "PrimaryQuantity",
    "SecondaryQuantity",
    "Priority",
    "OrderNumber",
    "DueDate",
    "ExpirationDate",
    "InhibitMoveFromStep",
    "InhibitShip",
    "SplitMergeRestrictionType",
    "ParentMaterial",
    "Location",
    "MoistureSensitivityLevel",
    "FloorLifeRemainingHours",
    "Manufacturer",
    "Supplier",
    "ManufacturerPartNumber",
    "ManufacturerLotNumber",
    "DateCode",
    "PurchaseOrderNumber",
    "BinCode",
    "CapacityClass",
    "IsRoHSCompliant",
  ],
};

const cachedTemplate: MasterDataTemplateDefinition = {
  workbookFileName: MASTER_DATA_TEMPLATE_WORKBOOK_FILE_NAME,
  sheets: Object.fromEntries(
    masterDataObjectTypes.map((objectType) => [
      objectType,
      {
        objectType,
        sheetName: masterDataSheetNames[objectType],
        headers: [...masterDataSheetHeaders[objectType]],
        sampleRow: {},
      } satisfies MasterDataSheetTemplate,
    ]),
  ) as Record<MasterDataObjectType, MasterDataSheetTemplate>,
};

export async function loadMasterDataTemplateDefinition(): Promise<MasterDataTemplateDefinition> {
  return cachedTemplate;
}

export async function createBlankMasterDataWorkbook(): Promise<Workbook> {
  const workbook = await createExcelJsWorkbook();
  const template = await loadMasterDataTemplateDefinition();

  masterDataObjectTypes.forEach((objectType) => {
    const sheetTemplate = template.sheets[objectType];
    const worksheet = workbook.addWorksheet(sheetTemplate.sheetName);
    worksheet.addRow(sheetTemplate.headers);
  });

  return workbook;
}
